Repository collective/collective.cover, pull requests merged in 2018-08, with the labels that each got.

#794 Fix retrieval of available image scales in tile layout configuration for Plone 5
  CHANGES.rst
  src/collective/cover/browser/configure.zcml
  src/collective/cover/browser/cover.py
  src/collective/cover/tests/test_scaling.robot
  src/collective/cover/tests/test_vocabularies.py
  src/collective/cover/tiles/configuration_widgets/namedimage.pt
Labels: plone 5, ready

#803 Remove deprecated adapters
  CHANGES.rst
  src/collective/cover/interfaces.py
  src/collective/cover/tiles/configure.zcml
  src/collective/cover/tiles/list.py
Labels: ready

#783 Remove upgrade steps for old, unsupported releases
  CHANGES.rst
  src/collective/cover/profiles.zcml
  src/collective/cover/tests/test_upgrades.py
  src/collective/cover/upgrades/__init__.py
  src/collective/cover/upgrades/configure.zcml
  src/collective/cover/upgrades/v11/__init__.py
  src/collective/cover/upgrades/v11/configure.zcml
  src/collective/cover/upgrades/v12/__init__.py
  src/collective/cover/upgrades/v12/configure.zcml
  src/collective/cover/upgrades/v13/__init__.py
  src/collective/cover/upgrades/v13/configure.zcml
Labels: enhancement

#800 Remove cover predefined Layouts
  CHANGES.rst
  docs/developer.rst
  docs/end-user.rst
  src/collective/cover/profiles/default/registry.xml
  src/collective/cover/profiles/testfixture/registry.xml
  src/collective/cover/tests/test_grid.py
  src/collective/cover/tests/test_widget_preview.py
Labels: plone 5, ready

#809 Remove hard dependency on plone.app.relationfield
  CHANGES.rst
  README.rst
  buildout.cfg
  setup.py
  src/collective/cover/configure.zcml
  src/collective/cover/profiles.zcml
  src/collective/cover/profiles/default/types/collective.cover.content.xml
  src/collective/cover/setuphandlers.py
  src/collective/cover/tests/test_cover.py
Labels: enhancement, ready

#812 Deprecate PFG tile
  CHANGES.rst
  README.rst
  docs/end-user.rst
  setup.py
  src/collective/cover/testing.py
  src/collective/cover/tests/test_pfg_tile.py
  src/collective/cover/tests/test_vocabularies.py
  src/collective/cover/tiles/pfg.py
  src/collective/cover/vocabularies.py
  versions-4.3.x.cfg
  versions-5.1.x.cfg
Labels: enhancement, in progress
